### ISSUE TITLE
procとchrootの順番を逆にしないとprocfsが見れなくなる

### ISSUE THREAD

**Issue by draftcode** [rrreeeyyy/container-internship#3]
https://github.com/rrreeeyyy/container-internship/blob/8a459c1131e8149df43adbd0cfe204ed9455eb36/02/examples/6.go#L52-L57

https://github.com/rrreeeyyy/container-internship/tree/8a459c1131e8149df43adbd0cfe204ed9455eb36/02#chroot--pivot_root

この部分は逆にしないと/procがchroot後に見えない気がします。

**Comment by rrreeeyyy** [comment]
確かにこの例だと proc が正しく見れなさそうですね。7 以降の例と合うように、chroot のケースでも事前に /root/chroot/proc を作成してそこにマウントするように #4 で変更しました。報告ありがとうございます。
